// Generated by gencpp from file DNT/AddTwoIntResponse.msg
// DO NOT EDIT!


#ifndef DNT_MESSAGE_ADDTWOINTRESPONSE_H
#define DNT_MESSAGE_ADDTWOINTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace DNT
{
template <class ContainerAllocator>
struct AddTwoIntResponse_
{
  typedef AddTwoIntResponse_<ContainerAllocator> Type;

  AddTwoIntResponse_()
    : sum(0)  {
    }
  AddTwoIntResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int64_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::DNT::AddTwoIntResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::DNT::AddTwoIntResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddTwoIntResponse_

typedef ::DNT::AddTwoIntResponse_<std::allocator<void> > AddTwoIntResponse;

typedef boost::shared_ptr< ::DNT::AddTwoIntResponse > AddTwoIntResponsePtr;
typedef boost::shared_ptr< ::DNT::AddTwoIntResponse const> AddTwoIntResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::DNT::AddTwoIntResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::DNT::AddTwoIntResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::DNT::AddTwoIntResponse_<ContainerAllocator1> & lhs, const ::DNT::AddTwoIntResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::DNT::AddTwoIntResponse_<ContainerAllocator1> & lhs, const ::DNT::AddTwoIntResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace DNT

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::DNT::AddTwoIntResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::DNT::AddTwoIntResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::DNT::AddTwoIntResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::DNT::AddTwoIntResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::DNT::AddTwoIntResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::DNT::AddTwoIntResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::DNT::AddTwoIntResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b88405221c77b1878a3cbbfff53428d7";
  }

  static const char* value(const ::DNT::AddTwoIntResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb88405221c77b187ULL;
  static const uint64_t static_value2 = 0x8a3cbbfff53428d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::DNT::AddTwoIntResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "DNT/AddTwoIntResponse";
  }

  static const char* value(const ::DNT::AddTwoIntResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::DNT::AddTwoIntResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 sum\n"
"\n"
"\n"
;
  }

  static const char* value(const ::DNT::AddTwoIntResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::DNT::AddTwoIntResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddTwoIntResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::DNT::AddTwoIntResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::DNT::AddTwoIntResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int64_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DNT_MESSAGE_ADDTWOINTRESPONSE_H
