// Generated by gencpp from file DNT/AddTwoInt.msg
// DO NOT EDIT!


#ifndef DNT_MESSAGE_ADDTWOINT_H
#define DNT_MESSAGE_ADDTWOINT_H

#include <ros/service_traits.h>


#include <DNT/AddTwoIntRequest.h>
#include <DNT/AddTwoIntResponse.h>


namespace DNT
{

struct AddTwoInt
{

typedef AddTwoIntRequest Request;
typedef AddTwoIntResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInt
} // namespace DNT


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::DNT::AddTwoInt > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::DNT::AddTwoInt&) { return value(); }
};

template<>
struct DataType< ::DNT::AddTwoInt > {
  static const char* value()
  {
    return "DNT/AddTwoInt";
  }

  static const char* value(const ::DNT::AddTwoInt&) { return value(); }
};


// service_traits::MD5Sum< ::DNT::AddTwoIntRequest> should match
// service_traits::MD5Sum< ::DNT::AddTwoInt >
template<>
struct MD5Sum< ::DNT::AddTwoIntRequest>
{
  static const char* value()
  {
    return MD5Sum< ::DNT::AddTwoInt >::value();
  }
  static const char* value(const ::DNT::AddTwoIntRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::DNT::AddTwoIntRequest> should match
// service_traits::DataType< ::DNT::AddTwoInt >
template<>
struct DataType< ::DNT::AddTwoIntRequest>
{
  static const char* value()
  {
    return DataType< ::DNT::AddTwoInt >::value();
  }
  static const char* value(const ::DNT::AddTwoIntRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::DNT::AddTwoIntResponse> should match
// service_traits::MD5Sum< ::DNT::AddTwoInt >
template<>
struct MD5Sum< ::DNT::AddTwoIntResponse>
{
  static const char* value()
  {
    return MD5Sum< ::DNT::AddTwoInt >::value();
  }
  static const char* value(const ::DNT::AddTwoIntResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::DNT::AddTwoIntResponse> should match
// service_traits::DataType< ::DNT::AddTwoInt >
template<>
struct DataType< ::DNT::AddTwoIntResponse>
{
  static const char* value()
  {
    return DataType< ::DNT::AddTwoInt >::value();
  }
  static const char* value(const ::DNT::AddTwoIntResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DNT_MESSAGE_ADDTWOINT_H
