// Generated by gencpp from file DNT/areacalResponse.msg
// DO NOT EDIT!


#ifndef DNT_MESSAGE_AREACALRESPONSE_H
#define DNT_MESSAGE_AREACALRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace DNT
{
template <class ContainerAllocator>
struct areacalResponse_
{
  typedef areacalResponse_<ContainerAllocator> Type;

  areacalResponse_()
    : area(0.0)  {
    }
  areacalResponse_(const ContainerAllocator& _alloc)
    : area(0.0)  {
  (void)_alloc;
    }



   typedef double _area_type;
  _area_type area;





  typedef boost::shared_ptr< ::DNT::areacalResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::DNT::areacalResponse_<ContainerAllocator> const> ConstPtr;

}; // struct areacalResponse_

typedef ::DNT::areacalResponse_<std::allocator<void> > areacalResponse;

typedef boost::shared_ptr< ::DNT::areacalResponse > areacalResponsePtr;
typedef boost::shared_ptr< ::DNT::areacalResponse const> areacalResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::DNT::areacalResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::DNT::areacalResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::DNT::areacalResponse_<ContainerAllocator1> & lhs, const ::DNT::areacalResponse_<ContainerAllocator2> & rhs)
{
  return lhs.area == rhs.area;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::DNT::areacalResponse_<ContainerAllocator1> & lhs, const ::DNT::areacalResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace DNT

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::DNT::areacalResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::DNT::areacalResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::DNT::areacalResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::DNT::areacalResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::DNT::areacalResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::DNT::areacalResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::DNT::areacalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "502b7bd5115b3b4f57d03446f9208d12";
  }

  static const char* value(const ::DNT::areacalResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x502b7bd5115b3b4fULL;
  static const uint64_t static_value2 = 0x57d03446f9208d12ULL;
};

template<class ContainerAllocator>
struct DataType< ::DNT::areacalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "DNT/areacalResponse";
  }

  static const char* value(const ::DNT::areacalResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::DNT::areacalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 area\n"
"\n"
;
  }

  static const char* value(const ::DNT::areacalResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::DNT::areacalResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.area);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct areacalResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::DNT::areacalResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::DNT::areacalResponse_<ContainerAllocator>& v)
  {
    s << indent << "area: ";
    Printer<double>::stream(s, indent + "  ", v.area);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DNT_MESSAGE_AREACALRESPONSE_H
