// Generated by gencpp from file DNT/areacalRequest.msg
// DO NOT EDIT!


#ifndef DNT_MESSAGE_AREACALREQUEST_H
#define DNT_MESSAGE_AREACALREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace DNT
{
template <class ContainerAllocator>
struct areacalRequest_
{
  typedef areacalRequest_<ContainerAllocator> Type;

  areacalRequest_()
    : l(0.0)
    , b(0.0)  {
    }
  areacalRequest_(const ContainerAllocator& _alloc)
    : l(0.0)
    , b(0.0)  {
  (void)_alloc;
    }



   typedef double _l_type;
  _l_type l;

   typedef double _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::DNT::areacalRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::DNT::areacalRequest_<ContainerAllocator> const> ConstPtr;

}; // struct areacalRequest_

typedef ::DNT::areacalRequest_<std::allocator<void> > areacalRequest;

typedef boost::shared_ptr< ::DNT::areacalRequest > areacalRequestPtr;
typedef boost::shared_ptr< ::DNT::areacalRequest const> areacalRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::DNT::areacalRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::DNT::areacalRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::DNT::areacalRequest_<ContainerAllocator1> & lhs, const ::DNT::areacalRequest_<ContainerAllocator2> & rhs)
{
  return lhs.l == rhs.l &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::DNT::areacalRequest_<ContainerAllocator1> & lhs, const ::DNT::areacalRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace DNT

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::DNT::areacalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::DNT::areacalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::DNT::areacalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::DNT::areacalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::DNT::areacalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::DNT::areacalRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::DNT::areacalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7095acba5fac068e513c8fba0ed6dd36";
  }

  static const char* value(const ::DNT::areacalRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7095acba5fac068eULL;
  static const uint64_t static_value2 = 0x513c8fba0ed6dd36ULL;
};

template<class ContainerAllocator>
struct DataType< ::DNT::areacalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "DNT/areacalRequest";
  }

  static const char* value(const ::DNT::areacalRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::DNT::areacalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 l\n"
"float64 b\n"
;
  }

  static const char* value(const ::DNT::areacalRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::DNT::areacalRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.l);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct areacalRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::DNT::areacalRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::DNT::areacalRequest_<ContainerAllocator>& v)
  {
    s << indent << "l: ";
    Printer<double>::stream(s, indent + "  ", v.l);
    s << indent << "b: ";
    Printer<double>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DNT_MESSAGE_AREACALREQUEST_H
