// Generated by gencpp from file DNT/areacal.msg
// DO NOT EDIT!


#ifndef DNT_MESSAGE_AREACAL_H
#define DNT_MESSAGE_AREACAL_H

#include <ros/service_traits.h>


#include <DNT/areacalRequest.h>
#include <DNT/areacalResponse.h>


namespace DNT
{

struct areacal
{

typedef areacalRequest Request;
typedef areacalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct areacal
} // namespace DNT


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::DNT::areacal > {
  static const char* value()
  {
    return "c222771ac5e7a31ae9d73f33968def15";
  }

  static const char* value(const ::DNT::areacal&) { return value(); }
};

template<>
struct DataType< ::DNT::areacal > {
  static const char* value()
  {
    return "DNT/areacal";
  }

  static const char* value(const ::DNT::areacal&) { return value(); }
};


// service_traits::MD5Sum< ::DNT::areacalRequest> should match
// service_traits::MD5Sum< ::DNT::areacal >
template<>
struct MD5Sum< ::DNT::areacalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::DNT::areacal >::value();
  }
  static const char* value(const ::DNT::areacalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::DNT::areacalRequest> should match
// service_traits::DataType< ::DNT::areacal >
template<>
struct DataType< ::DNT::areacalRequest>
{
  static const char* value()
  {
    return DataType< ::DNT::areacal >::value();
  }
  static const char* value(const ::DNT::areacalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::DNT::areacalResponse> should match
// service_traits::MD5Sum< ::DNT::areacal >
template<>
struct MD5Sum< ::DNT::areacalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::DNT::areacal >::value();
  }
  static const char* value(const ::DNT::areacalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::DNT::areacalResponse> should match
// service_traits::DataType< ::DNT::areacal >
template<>
struct DataType< ::DNT::areacalResponse>
{
  static const char* value()
  {
    return DataType< ::DNT::areacal >::value();
  }
  static const char* value(const ::DNT::areacalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DNT_MESSAGE_AREACAL_H
